apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: cabpk-controller-manager
  name: cabpk-controller-manager
  namespace: cabpk-system
spec:
  template:
    metadata:
      labels:
        control-plane: cabpk-controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --v=4
        - --enable-leader-election
        - --bootstrap-token-ttl=30m
        image: us.gcr.io/k8s-artifacts-prod/capi-kubeadm/cluster-api-kubeadm-controller:v0.1.2
        imagePullPolicy: Always
        name: manager
