apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- provider-components-kubeadm.yaml
- provider-components-cluster-api.yaml
- provider-components-azurestackhci.yaml
patchesStrategicMerge:
- manager_tolerations_patch.yaml
- manager_networking_patch.yaml
- kubeadm_token_patch.yaml
