apiVersion: v1
kind: Secret
metadata:
  name: manager-bootstrap-credentials
  namespace: system
type: Opaque
data:
  cloudagent-fqdn: ${CLOUDAGENT_FQDN_B64}
  wssd-debug-mode: ${WSSD_DEBUG_MODE_B64}
  binary-location: ${BINARY_LOCATION_B64}